const TEST = 'TEST';
const SET_CATEGORY = 'SET_CATEGORY';
const SET_PRODUCTS = 'SET_PRODUCTS';
const SET_ROOT_CATEGORY_ID = 'SET_ROOT_CATEGORY_ID';
export default { TEST, SET_CATEGORY, SET_PRODUCTS, SET_ROOT_CATEGORY_ID };
