const SET_CATEGORY = 'SET_CATEGORY';
const SET_CATEGORY_LOADING = 'SET_CATEGORY_LOADING'
const SET_PRODUCTS = 'SET_PRODUCTS';
const SET_ROOT_CATEGORY_ID = 'SET_ROOT_CATEGORY_ID';

const SET_MODAL_PRODUCT = 'SET_MODAL_PRODUCT'
const SET_MODAL_PRODUCT_STATE = 'SET_MODAL_PRODUCT_STATE';
const SET_LOADING_MODAL_PRODUCT = 'SET_LOADING_MODAL_PRODUCT';
const SET_MODAL_CURRENT_PICTURE = 'SET_MODAL_CURRENT_PICTURE';

const SET_CART = 'SET_CART';
const CART_INC_POSITION = 'CART_INC_POSITION';
const CART_DEC_POSITION = 'CART_DEC_POSITION';
const CART_RESET_POSITION = 'CART_RESET_POSITION';

const SET_FULL_PRODUCT = 'SET_FULL_PRODUCT'
const SET_LOADING_FULL_PRODUCT = 'SET_LOADING_FULL_PRODUCT';
const SET_FULL_CURRENT_PICTURE = 'SET_FULL_CURRENT_PICTURE';

const SET_SEARCH_KEYWORD = 'SET_SEARCH_KEYWORD';
const SET_SEARCH_PRODUCTS = 'SET_SEARCH_PRODUCTS';
const SET_HISTORY = 'SET_HISTORY';

const SET_FILTERS = 'SET_FILTERS';

const SET_COLLECTIONS = 'SET_COLLECTIONS';
const SET_COLLECTION = 'SET_COLLECTION';
const SET_COLLECTION_LOADING = 'SET_COLLECTION_LOADING';

const SET_POSTS = 'SET_POSTS';
const SET_POST = 'SET_POST';
const SET_POST_LOADING = 'SET_POST_LOADING';

export default {
  SET_CATEGORY, SET_PRODUCTS, SET_ROOT_CATEGORY_ID, SET_CATEGORY_LOADING,
  SET_MODAL_PRODUCT, SET_MODAL_PRODUCT_STATE,
  SET_LOADING_MODAL_PRODUCT, SET_MODAL_CURRENT_PICTURE,
  SET_CART, CART_INC_POSITION, CART_DEC_POSITION, CART_RESET_POSITION,
  SET_FULL_PRODUCT, SET_LOADING_FULL_PRODUCT, SET_FULL_CURRENT_PICTURE,
  SET_SEARCH_KEYWORD, SET_SEARCH_PRODUCTS, SET_HISTORY,
  SET_FILTERS, SET_COLLECTIONS, SET_COLLECTION, SET_COLLECTION_LOADING,
  SET_POST, SET_POSTS, SET_POST_LOADING
};
