const SET_CATEGORY = 'SET_CATEGORY';
const SET_PRODUCTS = 'SET_PRODUCTS';
const SET_ROOT_CATEGORY_ID = 'SET_ROOT_CATEGORY_ID';

const SET_MODAL_PRODUCT = 'SET_MODAL_PRODUCT'
const SET_MODAL_PRODUCT_STATE = 'SET_MODAL_PRODUCT_STATE';
const SET_LOADING_MODAL_PRODUCT = 'SET_LOADING_MODAL_PRODUCT';
const SET_MODAL_CURRENT_PICTURE = 'SET_MODAL_CURRENT_PICTURE';

const SET_CART = 'SET_CART';

export default {
  SET_CATEGORY, SET_PRODUCTS, SET_ROOT_CATEGORY_ID,
  SET_MODAL_PRODUCT, SET_MODAL_PRODUCT_STATE,
  SET_LOADING_MODAL_PRODUCT, SET_MODAL_CURRENT_PICTURE,
  SET_CART
};
