const SET_BANNER = 'SET_BANNER';
const SET_BANNERS = 'SET_BANNERS';
const SET_BANNERS_LOADING = 'SET_BANNERS_LOADING';
const SET_BANNERS_FROM_SERVER = 'SET_BANNERS_FROM_SERVER';
const SET_BANNER_ERRORS = 'SET_BANNER_ERRORS';

export default {SET_BANNER, SET_BANNERS, SET_BANNERS_FROM_SERVER, SET_BANNERS_LOADING, SET_BANNER_ERRORS}
