const SET_CATEGORY = 'SET_CATEGORY';
const SET_CATEGORIES = 'SET_CATEGORIES';
const SET_CATEGORIES_LOADING = 'SET_CATEGORIES_LOADING';
const SET_CATEGORIES_FROM_SERVER = 'SET_CATEGORIES_FROM_SERVER';
const SET_CATEGORY_ERRORS = 'SET_CATEGORY_ERRORS';

export default {SET_CATEGORY, SET_CATEGORIES, SET_CATEGORIES_FROM_SERVER, SET_CATEGORIES_LOADING, SET_CATEGORY_ERRORS}
