const SET_COLLECTION = 'SET_COLLECTION';
const SET_COLLECTIONS = 'SET_COLLECTIONS';
const SET_COLLECTIONS_LOADING = 'SET_COLLECTIONS_LOADING';
const SET_COLLECTIONS_FROM_SERVER = 'SET_COLLECTIONS_FROM_SERVER';
const SET_COLLECTION_ERRORS = 'SET_COLLECTION_ERRORS';

export default {SET_COLLECTION, SET_COLLECTIONS, SET_COLLECTIONS_FROM_SERVER, SET_COLLECTIONS_LOADING, SET_COLLECTION_ERRORS}
