const SET_BANNER = 'SET_BANNER';
const SET_BANNERS = 'SET_BANNERS';
const SET_BANNERS_LOADING = 'SET_BANNERS_LOADING';
const SET_BANNERS_FROM_SERVER = 'SET_BANNERS_FROM_SERVER';

export default {SET_BANNER, SET_BANNERS, SET_BANNERS_FROM_SERVER, SET_BANNERS_LOADING}
