const SET_ORDER = 'SET_ORDER';
const SET_ORDERS = 'SET_ORDERS';
const SET_ORDERS_LOADING = 'SET_ORDERS_LOADING';
const SET_ORDERS_FROM_SERVER = 'SET_ORDERS_FROM_SERVER';
const SET_ORDER_ERRORS = 'SET_ORDER_ERRORS';

export default {SET_ORDER, SET_ORDERS, SET_ORDERS_FROM_SERVER, SET_ORDERS_LOADING, SET_ORDER_ERRORS}
