const SET_POST = 'SET_POST';
const SET_POSTS = 'SET_POSTS';
const SET_POSTS_LOADING = 'SET_POSTS_LOADING';
const SET_POSTS_FROM_SERVER = 'SET_POSTS_FROM_SERVER';
const SET_POST_ERRORS = 'SET_POST_ERRORS';

export default {SET_POST, SET_POSTS, SET_POSTS_FROM_SERVER, SET_POSTS_LOADING, SET_POST_ERRORS}
