const SET_PRODUCT = 'SET_PRODUCT';
const SET_PRODUCTS = 'SET_PRODUCTS';
const SET_PRODUCTS_LOADING = 'SET_PRODUCTS_LOADING';
const SET_PRODUCTS_FROM_SERVER = 'SET_PRODUCTS_FROM_SERVER';
const SET_PRODUCT_ERRORS = 'SET_PRODUCT_ERRORS';

export default {SET_PRODUCT, SET_PRODUCTS, SET_PRODUCTS_FROM_SERVER, SET_PRODUCTS_LOADING, SET_PRODUCT_ERRORS}
